services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - ZIM_DIR=/app/data/zim
      - SESSION_TIMEOUT=30
      - SECRET_KEY=secret

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  # Provision your own LLM service and update the config via the admin UI
